export const GET_SHOPPING_CART_ITEMS_REQUEST =
  "GET_SHOPPING_CART_ITEMS_REQUEST";
export const GET_SHOPPING_CART_ITEMS_SUCCESS =
  "GET_SHOPPING_CART_ITEMS_SUCCESS";
export const GET_SHOPPING_CART_ITEMS_FAIL = "GET_SHOPPING_CART_ITEMS_FAIL";
