export const GET_SHOPPING_CART_ITEMS_REQUEST =
  "GET_SHOPPING_CART_ITEMS_REQUEST";
export const GET_SHOPPING_CART_ITEMS_SUCCESS =
  "GET_SHOPPING_CART_ITEMS_SUCCESS";
  export const GET_SHOPPING_CART_ITEMS_FAIL = "GET_SHOPPING_CART_ITEMS_FAIL";

  export const ADD_TO_SHOPPING_CART_FAIL = "ADD_TO_SHOPPING_CART_FAIL";
  export const ADD_TO_SHOPPING_CART_REQUEST = "ADD_TO_SHOPPING_CART_REQUEST";
export const ADD_TO_SHOPPING_CART_SUCCESS = "ADD_TO_SHOPPING_CART_SUCCESS";

